-- Shinymoon signed GameSense loader
-- Supply-chain integrity only: this client-side loader does not claim secrecy or DRM.

local SL = {
    version = 1,
    state = {
        phase = "cold",
        detail = "",
        shutdown = false,
        generation = 0,
        request_serial = 0,
        request = nil,
        high_water = nil,
        verified_candidate = nil,
        failure_category = nil,
        active = nil,
        cache_attempted = false,
        retries = 0,
    },
    limits = {
        metadata_bytes = 128 * 1024,
        module_bytes = 1024 * 1024,
        bundle_bytes = 2 * 1024 * 1024,
        module_count = 32,
        dependency_depth = 16,
        json_depth = 24,
        request_timeout = 12,
        future_skew = 300,
        max_retries = 8,
        role_lifetime = {
            timestamp = 2 * 24 * 60 * 60,
            snapshot = 14 * 24 * 60 * 60,
            targets = 31 * 24 * 60 * 60,
        },
    },
    crypto = {
        bitops = nil,
        open = false,
    },
}

SL.json_kind = setmetatable({}, { __mode = "k" })

-- This public-only block is generated by tools/secure-loader/publish.mjs.
-- The placeholders deliberately fail configuration validation.
-- SECURE_LOADER_CONFIG_BEGIN
local CONFIG = {
    metadata_base_url = "https://raw.githubusercontent.com/dfs736037-star/shinymoon_repo/master/gamesense/loader-metadata",
    bundle_id = "shinymoon",
    channel = "stable",
    allowed_targets = {
        { owner = "dfs736037-star", repo = "shinymoon_repo", path_prefix = "gamesense/modules/" },
    },
    trusted_keys = {
        ["snapshot-a"] = { x = "9064d600443dd9cb6cb860b47911bf6354fc8dd39f6ba39dddee78ae8f45c6c4", y = "e4be067de1113515f67778a7d99390375ff1c8486268333c62129dd8ac80a99c" },
        ["targets-a"] = { x = "e94e52cab2095a8230e7a8eb43ddc5185c9b047e27a5d8028afbd0557f0d1998", y = "3573ae237c0060fcb87fb23f69ad4119478a1f4c3b2d4d75133b918ed1ec549c" },
        ["timestamp-a"] = { x = "47c4b58d3d66146db91978eac7d55ceb955c72a164296627e22d8731c8070650", y = "28f1708a357aa5fff5dd66e9c514b1ce80b023b3ede7808419d9fe63f1b11fdb" },
    },
    roles = {
        timestamp = { threshold = 1, key_ids = { "timestamp-a" } },
        snapshot = { threshold = 1, key_ids = { "snapshot-a" } },
        targets = { threshold = 1, key_ids = { "targets-a" } },
    },
}
-- SECURE_LOADER_CONFIG_END

SL.constants = {
    sha256_abc = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
    self_test_message = "shinymoon-loader-cng-self-test-v1",
    self_test_x = "184c4e4d4a2a40fb5779f824ba11941eba73c525a74c2109712ed2687abb16c6",
    self_test_y = "c86fbd4230677fd75f50a454b86ea66dc700019a3dd021c7d4ed2da0596a7b62",
    self_test_signature = "RI4fg2Cumk4jEahyK/KGhTV7dD1FdJHU41YED6BHKm2izpo4MG9O0H6fWg5hCCVNIA629T7IWkQuO4Fy6UPHUg==",
}

SL.base64_alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
SL.base64_values = {}
for i = 1, #SL.base64_alphabet do
    SL.base64_values[SL.base64_alphabet:sub(i, i)] = i - 1
end

function SL.safe_text(value, maximum)
    local text = tostring(value or "unknown")
    text = text:gsub("[%c]", " ")
    local limit = maximum or 240
    if #text > limit then
        text = text:sub(1, limit) .. "..."
    end
    return text
end

function SL.log(level, message)
    local text = "[shinymoon loader] " .. SL.safe_text(message, 320)
    if type(client) ~= "table" then
        return
    end
    if level == "error" and type(client.error_log) == "function" then
        pcall(client.error_log, text)
    elseif type(client.log) == "function" then
        pcall(client.log, text)
    end
end

function SL.set_phase(phase, detail, level)
    SL.state.phase = phase
    SL.state.detail = SL.safe_text(detail or "", 240)
    if detail and detail ~= "" then
        SL.log(level or "info", phase .. ": " .. SL.state.detail)
    end
end

function SL.hex_decode(value, expected_bytes)
    if type(value) ~= "string" or value:find("[^0-9a-f]") or (#value % 2) ~= 0 then
        return nil, "hex must be lowercase and even-length"
    end
    if expected_bytes and #value ~= expected_bytes * 2 then
        return nil, "hex has the wrong byte length"
    end
    local out = {}
    for index = 1, #value, 2 do
        local byte = tonumber(value:sub(index, index + 1), 16)
        if not byte then
            return nil, "hex contains an invalid byte"
        end
        out[#out + 1] = string.char(byte)
    end
    return table.concat(out)
end

function SL.hex_encode(value)
    local out = {}
    for index = 1, #value do
        out[index] = string.format("%02x", value:byte(index))
    end
    return table.concat(out)
end

function SL.base64_encode(value)
    local out = {}
    local index = 1
    while index <= #value do
        local a = value:byte(index) or 0
        local b = value:byte(index + 1)
        local c = value:byte(index + 2)
        local packed = a * 65536 + (b or 0) * 256 + (c or 0)
        local first = math.floor(packed / 262144) % 64
        local second = math.floor(packed / 4096) % 64
        local third = math.floor(packed / 64) % 64
        local fourth = packed % 64
        out[#out + 1] = SL.base64_alphabet:sub(first + 1, first + 1)
        out[#out + 1] = SL.base64_alphabet:sub(second + 1, second + 1)
        out[#out + 1] = b and SL.base64_alphabet:sub(third + 1, third + 1) or "="
        out[#out + 1] = c and SL.base64_alphabet:sub(fourth + 1, fourth + 1) or "="
        index = index + 3
    end
    return table.concat(out)
end

function SL.base64_decode(value, expected_bytes)
    if type(value) ~= "string" or #value == 0 or (#value % 4) ~= 0 then
        return nil, "base64 length is invalid"
    end
    local body = value:gsub("=+$", "")
    local padding = #value - #body
    if padding > 2 or body:find("=") or body:find("[^A-Za-z0-9+/]") then
        return nil, "base64 alphabet or padding is invalid"
    end
    local out = {}
    for index = 1, #value, 4 do
        local ca = value:sub(index, index)
        local cb = value:sub(index + 1, index + 1)
        local cc = value:sub(index + 2, index + 2)
        local cd = value:sub(index + 3, index + 3)
        local a = SL.base64_values[ca]
        local b = SL.base64_values[cb]
        local c = cc == "=" and 0 or SL.base64_values[cc]
        local d = cd == "=" and 0 or SL.base64_values[cd]
        if a == nil or b == nil or c == nil or d == nil then
            return nil, "base64 contains an invalid quartet"
        end
        if (cc == "=" and cd ~= "=") or (index < #value - 3 and (cc == "=" or cd == "=")) then
            return nil, "base64 padding is not final"
        end
        local packed = a * 262144 + b * 4096 + c * 64 + d
        out[#out + 1] = string.char(math.floor(packed / 65536) % 256)
        if cc ~= "=" then
            out[#out + 1] = string.char(math.floor(packed / 256) % 256)
        end
        if cd ~= "=" then
            out[#out + 1] = string.char(packed % 256)
        end
    end
    local decoded = table.concat(out)
    if expected_bytes and #decoded ~= expected_bytes then
        return nil, "base64 has the wrong decoded length"
    end
    if SL.base64_encode(decoded) ~= value then
        return nil, "base64 is not canonical padded encoding"
    end
    return decoded
end

-- GameSense LuaJIT strips ffi.load/ffi.C, so Windows CNG is unreachable. SHA-256
-- and ECDSA P-256 are implemented in pure Lua over the LuaJIT `bit` library.
do
    local ok_bit, bitlib = pcall(require, "bit")
    local bit = (ok_bit and bitlib) or rawget(_G, "bit") or rawget(_G, "bit32")
    SL.crypto.bitops = bit
    local band = bit and bit.band
    local bxor = bit and bit.bxor
    local bor = bit and bit.bor
    local lshift = bit and bit.lshift
    local rshift = bit and bit.rshift

    local function u32(x)
        return x % 4294967296
    end
    local function rotr(x, n)
        x = u32(x)
        return u32(bor(rshift(x, n), lshift(x, 32 - n)))
    end
    local function xor3(a, b, c)
        return bxor(bxor(a, b), c)
    end

    local K = {
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
        0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
        0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
        0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
        0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
        0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
        0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
    }

    function SL.sha256_raw(value)
        if not SL.crypto.bitops then
            return nil, "bit library unavailable (LuaJIT required)"
        end
        if type(value) ~= "string" then
            return nil, "SHA256 input must be a string"
        end
        local h0, h1, h2, h3 = 0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a
        local h4, h5, h6, h7 = 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19
        local bitlen = #value * 8
        local padded = value .. "\128"
        while (#padded % 64) ~= 56 do
            padded = padded .. "\0"
        end
        local hi = math.floor(bitlen / 4294967296)
        local lo = bitlen % 4294967296
        padded = padded .. string.char(
            band(rshift(hi, 24), 255), band(rshift(hi, 16), 255), band(rshift(hi, 8), 255), band(hi, 255),
            band(rshift(lo, 24), 255), band(rshift(lo, 16), 255), band(rshift(lo, 8), 255), band(lo, 255))
        local w = {}
        for block = 1, #padded, 64 do
            for i = 1, 16 do
                local j = block + (i - 1) * 4
                w[i] = padded:byte(j) * 16777216 + padded:byte(j + 1) * 65536
                    + padded:byte(j + 2) * 256 + padded:byte(j + 3)
            end
            for i = 17, 64 do
                local a = w[i - 15]
                local b = w[i - 2]
                local s0 = xor3(rotr(a, 7), rotr(a, 18), rshift(a, 3))
                local s1 = xor3(rotr(b, 17), rotr(b, 19), rshift(b, 10))
                w[i] = u32(w[i - 16] + s0 + w[i - 7] + s1)
            end
            local a, b, c, d = h0, h1, h2, h3
            local e, f, g, h = h4, h5, h6, h7
            for i = 1, 64 do
                local s1 = xor3(rotr(e, 6), rotr(e, 11), rotr(e, 25))
                local ch = bxor(band(e, f), band(u32(-e - 1), g))
                local t1 = u32(h + s1 + ch + K[i] + w[i])
                local s0 = xor3(rotr(a, 2), rotr(a, 13), rotr(a, 22))
                local maj = xor3(band(a, b), band(a, c), band(b, c))
                local t2 = u32(s0 + maj)
                h = g; g = f; f = e; e = u32(d + t1)
                d = c; c = b; b = a; a = u32(t1 + t2)
            end
            h0 = u32(h0 + a); h1 = u32(h1 + b); h2 = u32(h2 + c); h3 = u32(h3 + d)
            h4 = u32(h4 + e); h5 = u32(h5 + f); h6 = u32(h6 + g); h7 = u32(h7 + h)
        end
        local function word(x)
            return string.char(band(rshift(x, 24), 255), band(rshift(x, 16), 255),
                band(rshift(x, 8), 255), band(x, 255))
        end
        return word(h0) .. word(h1) .. word(h2) .. word(h3)
            .. word(h4) .. word(h5) .. word(h6) .. word(h7)
    end
end

function SL.crypto_open()
    if not SL.crypto.bitops then
        return nil, "bit library unavailable (LuaJIT with the bit library is required)"
    end
    SL.crypto.open = true
    return true
end

function SL.crypto_close()
    SL.crypto.open = false
end

function SL.sha256_hex(value)
    local raw, hash_error = SL.sha256_raw(value)
    if not raw then
        return nil, hash_error
    end
    return SL.hex_encode(raw)
end

-- ECDSA P-256 verification over pure-Lua big integers (base 2^24 limbs).
-- ponytail: bn_mod is bit-at-a-time long division. Correct but not fast; each
-- verify is a few thousand mulmods. Runs a handful of times at load, so the
-- cost is acceptable. Upgrade path if latency bites: NIST P-256 Solinas
-- fast-reduction to replace the general division in the mod-p hot path.
do
    local BASE = 16777216 -- 2^24
    local floor = math.floor

    local function bn_norm(a)
        local n = #a
        while n > 1 and a[n] == 0 do a[n] = nil; n = n - 1 end
        return a
    end
    local function bn_copy(a)
        local r = {}
        for i = 1, #a do r[i] = a[i] end
        return r
    end
    local function bn_zero() return { 0 } end
    local function bn_is_zero(a) return #a == 1 and a[1] == 0 end
    local function bn_from_int(x)
        if x == 0 then return { 0 } end
        local r = {}
        while x > 0 do r[#r + 1] = x % BASE; x = floor(x / BASE) end
        return r
    end
    local ONE = bn_from_int(1)
    local TWO = bn_from_int(2)
    local C256 = bn_from_int(256)
    local C3 = bn_from_int(3)
    local C4 = bn_from_int(4)
    local C8 = bn_from_int(8)

    local function bn_cmp(a, b)
        if #a ~= #b then return #a < #b and -1 or 1 end
        for i = #a, 1, -1 do
            if a[i] ~= b[i] then return a[i] < b[i] and -1 or 1 end
        end
        return 0
    end
    local function bn_add(a, b)
        local r = {}
        local carry = 0
        local n = #a > #b and #a or #b
        for i = 1, n do
            local s = (a[i] or 0) + (b[i] or 0) + carry
            if s >= BASE then r[i] = s - BASE; carry = 1 else r[i] = s; carry = 0 end
        end
        if carry > 0 then r[n + 1] = carry end
        return r
    end
    local function bn_sub(a, b) -- assumes a >= b
        local r = {}
        local borrow = 0
        for i = 1, #a do
            local s = a[i] - (b[i] or 0) - borrow
            if s < 0 then r[i] = s + BASE; borrow = 1 else r[i] = s; borrow = 0 end
        end
        return bn_norm(r)
    end
    local function bn_shl1(a)
        local r = {}
        local carry = 0
        for i = 1, #a do
            local s = a[i] * 2 + carry
            if s >= BASE then r[i] = s - BASE; carry = 1 else r[i] = s; carry = 0 end
        end
        if carry > 0 then r[#a + 1] = carry end
        return r
    end
    local function bn_mul(a, b)
        local r = {}
        for i = 1, #a + #b do r[i] = 0 end
        for i = 1, #a do
            local carry = 0
            local ai = a[i]
            for j = 1, #b do
                local idx = i + j - 1
                local s = r[idx] + ai * b[j] + carry
                carry = floor(s / BASE)
                r[idx] = s - carry * BASE
            end
            r[i + #b] = r[i + #b] + carry
        end
        return bn_norm(r)
    end
    local function bn_bitlen(a)
        local top = a[#a]
        local bits = (#a - 1) * 24
        while top > 0 do bits = bits + 1; top = floor(top / 2) end
        return bits
    end
    local function bn_testbit(a, i)
        local limb = floor(i / 24) + 1
        if limb > #a then return 0 end
        return floor(a[limb] / 2 ^ (i % 24)) % 2
    end
    local function bn_mod(a, m)
        if bn_cmp(a, m) < 0 then return bn_copy(a) end
        local r = bn_zero()
        for i = bn_bitlen(a) - 1, 0, -1 do
            r = bn_shl1(r)
            if bn_testbit(a, i) == 1 then r[1] = r[1] + 1 end
            if bn_cmp(r, m) >= 0 then r = bn_sub(r, m) end
        end
        return bn_norm(r)
    end
    local function bn_mulmod(a, b, m) return bn_mod(bn_mul(a, b), m) end
    local function bn_addmod(a, b, m)
        local s = bn_add(a, b)
        if bn_cmp(s, m) >= 0 then s = bn_sub(s, m) end
        return s
    end
    local function bn_submod(a, b, m)
        if bn_cmp(a, b) >= 0 then return bn_sub(a, b) end
        return bn_sub(bn_add(a, m), b)
    end
    local function bn_modpow(base, e, m)
        local result = bn_from_int(1)
        base = bn_mod(base, m)
        for i = 0, bn_bitlen(e) - 1 do
            if bn_testbit(e, i) == 1 then result = bn_mulmod(result, base, m) end
            base = bn_mulmod(base, base, m)
        end
        return result
    end
    local function bn_invmod(a, m) return bn_modpow(a, bn_sub(m, TWO), m) end
    local function bn_from_bytes(s)
        local r = bn_zero()
        for i = 1, #s do
            r = bn_add(bn_mul(r, C256), bn_from_int(s:byte(i)))
        end
        return bn_norm(r)
    end
    local HEXVAL = {}
    for i = 0, 9 do HEXVAL[string.char(48 + i)] = i end
    for i = 0, 5 do HEXVAL[string.char(97 + i)] = 10 + i end
    local function bn_from_hex(h)
        if type(h) ~= "string" or #h % 2 ~= 0 then return nil end
        local bytes = {}
        for i = 1, #h, 2 do
            local a = HEXVAL[h:sub(i, i)]
            local b = HEXVAL[h:sub(i + 1, i + 1)]
            if not a or not b then return nil end
            bytes[#bytes + 1] = string.char(a * 16 + b)
        end
        return bn_from_bytes(table.concat(bytes))
    end

    local P = bn_from_hex("ffffffff00000001000000000000000000000000ffffffffffffffffffffffff")
    local N = bn_from_hex("ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551")
    local Bcurve = bn_from_hex("5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b")
    local GX = bn_from_hex("6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296")
    local GY = bn_from_hex("4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5")

    local function fadd(a, b) return bn_addmod(a, b, P) end
    local function fsub(a, b) return bn_submod(a, b, P) end
    local function fmul(a, b) return bn_mulmod(a, b, P) end
    local INFINITY = { X = ONE, Y = ONE, Z = bn_zero() }

    local function jac_double(pt)
        if bn_is_zero(pt.Z) then return pt end
        local X, Y, Z = pt.X, pt.Y, pt.Z
        local A = fmul(Y, Y)
        local Bc = fmul(fmul(C4, X), A)
        local C = fmul(fmul(C8, A), A)
        local Z2 = fmul(Z, Z)
        local D = fmul(C3, fmul(fsub(X, Z2), fadd(X, Z2)))
        local X3 = fsub(fmul(D, D), fadd(Bc, Bc))
        local Y3 = fsub(fmul(D, fsub(Bc, X3)), C)
        local Z3 = fmul(fmul(TWO, Y), Z)
        return { X = X3, Y = Y3, Z = Z3 }
    end
    local function jac_add(p1, p2)
        if bn_is_zero(p1.Z) then return p2 end
        if bn_is_zero(p2.Z) then return p1 end
        local X1, Y1, Z1 = p1.X, p1.Y, p1.Z
        local X2, Y2, Z2 = p2.X, p2.Y, p2.Z
        local Z1Z1 = fmul(Z1, Z1)
        local Z2Z2 = fmul(Z2, Z2)
        local U1 = fmul(X1, Z2Z2)
        local U2 = fmul(X2, Z1Z1)
        local S1 = fmul(Y1, fmul(Z2, Z2Z2))
        local S2 = fmul(Y2, fmul(Z1, Z1Z1))
        if bn_cmp(U1, U2) == 0 then
            if bn_cmp(S1, S2) ~= 0 then return INFINITY end
            return jac_double(p1)
        end
        local H = fsub(U2, U1)
        local R = fsub(S2, S1)
        local HH = fmul(H, H)
        local HHH = fmul(H, HH)
        local U1HH = fmul(U1, HH)
        local X3 = fsub(fsub(fmul(R, R), HHH), fadd(U1HH, U1HH))
        local Y3 = fsub(fmul(R, fsub(U1HH, X3)), fmul(S1, HHH))
        local Z3 = fmul(fmul(Z1, Z2), H)
        return { X = X3, Y = Y3, Z = Z3 }
    end
    local function jac_mul(k, pt)
        local result = INFINITY
        for i = bn_bitlen(k) - 1, 0, -1 do
            result = jac_double(result)
            if bn_testbit(k, i) == 1 then result = jac_add(result, pt) end
        end
        return result
    end
    local function on_curve(x, y)
        local left = fmul(y, y)
        local right = fadd(fsub(fmul(fmul(x, x), x), fmul(C3, x)), Bcurve)
        return bn_cmp(left, right) == 0
    end

    -- message: bytes to hash; signature_base64: P1363 r||s; x_hex/y_hex: public key.
    function SL.verify_p256(message, signature_base64, x_hex, y_hex)
        if type(message) ~= "string" then
            return nil, "signature message must be a string"
        end
        local signature, signature_error = SL.base64_decode(signature_base64, 64)
        if not signature then
            return nil, signature_error
        end
        local qx = bn_from_hex(x_hex)
        local qy = bn_from_hex(y_hex)
        if not qx or not qy then
            return nil, "public key hex is malformed"
        end
        local hash, hash_error = SL.sha256_raw(message)
        if not hash then
            return nil, hash_error
        end
        local r = bn_from_bytes(signature:sub(1, 32))
        local s = bn_from_bytes(signature:sub(33, 64))
        if bn_is_zero(r) or bn_cmp(r, N) >= 0 then return false, "signature r out of range" end
        if bn_is_zero(s) or bn_cmp(s, N) >= 0 then return false, "signature s out of range" end
        if bn_cmp(qx, P) >= 0 or bn_cmp(qy, P) >= 0 then return nil, "public key coordinate out of range" end
        if not on_curve(qx, qy) then return nil, "public key is not on the curve" end
        local e = bn_mod(bn_from_bytes(hash), N)
        local w = bn_invmod(s, N)
        local u1 = bn_mulmod(e, w, N)
        local u2 = bn_mulmod(r, w, N)
        local point = jac_add(jac_mul(u1, { X = GX, Y = GY, Z = ONE }),
            jac_mul(u2, { X = qx, Y = qy, Z = ONE }))
        if bn_is_zero(point.Z) then return false, "signature reduces to point at infinity" end
        local zinv = bn_invmod(point.Z, P)
        local x = fmul(point.X, fmul(zinv, zinv))
        if bn_cmp(bn_mod(x, N), r) == 0 then
            return true
        end
        return false, "signature does not verify"
    end
end

function SL.crypto_self_test()
    local abc, hash_error = SL.sha256_hex("abc")
    if abc ~= SL.constants.sha256_abc then
        return nil, hash_error or "SHA256 known-answer mismatch"
    end
    local valid, verify_error = SL.verify_p256(
        SL.constants.self_test_message,
        SL.constants.self_test_signature,
        SL.constants.self_test_x,
        SL.constants.self_test_y
    )
    if valid ~= true then
        return nil, verify_error or "ECDSA known-answer verification failed"
    end
    local tampered, tamper_error = SL.verify_p256(
        SL.constants.self_test_message .. "!",
        SL.constants.self_test_signature,
        SL.constants.self_test_x,
        SL.constants.self_test_y
    )
    if tampered ~= false then
        return nil, tamper_error or "ECDSA tamper self-test did not reject"
    end
    return true
end

function SL.raise(message)
    error(SL.safe_text(message, 360), 0)
end

function SL.expect(condition, message)
    if not condition then
        SL.raise(message)
    end
    return condition
end

function SL.assert_ascii(value, label, minimum, maximum)
    SL.expect(type(value) == "string", label .. " must be a string")
    SL.expect(#value >= (minimum or 1) and #value <= (maximum or 256), label .. " length is outside bounds")
    for index = 1, #value do
        local byte = value:byte(index)
        SL.expect(byte >= 0x20 and byte <= 0x7e, label .. " must be printable ASCII")
    end
    return value
end

function SL.assert_integer(value, label, minimum, maximum)
    local upper = maximum or 9007199254740991
    SL.expect(type(value) == "number" and value == math.floor(value), label .. " must be an integer")
    SL.expect(value >= (minimum or 0) and value <= upper, label .. " is outside integer bounds")
    return value
end

function SL.integer_text(value)
    SL.assert_integer(value, "canonical integer", 0)
    return string.format("%.0f", value)
end

function SL.valid_id(value, label)
    SL.assert_ascii(value, label, 1, 64)
    SL.expect(value:match("^[a-z][a-z0-9_.%-]*$") ~= nil, label .. " has an invalid identifier")
    return value
end

function SL.valid_owner_repo(value, label)
    SL.assert_ascii(value, label, 1, 100)
    SL.expect(value:match("^[A-Za-z0-9_.%-]+$") ~= nil, label .. " has an invalid owner/repository name")
    return value
end

function SL.valid_digest(value, label)
    SL.expect(type(value) == "string" and #value == 64 and value:match("^[0-9a-f]+$") ~= nil,
        label .. " must be a lowercase SHA-256 digest")
    return value
end

function SL.exact_keys(value, expected, label)
    SL.expect(type(value) == "table", label .. " must be an object")
    SL.expect(SL.json_kind[value] == nil or SL.json_kind[value] == "object", label .. " must not be an array")
    local allowed = {}
    for index = 1, #expected do
        allowed[expected[index]] = true
        SL.expect(value[expected[index]] ~= nil, label .. " is missing " .. expected[index])
    end
    local count = 0
    for key in pairs(value) do
        count = count + 1
        SL.expect(type(key) == "string" and allowed[key], label .. " has an unexpected key")
    end
    SL.expect(count == #expected, label .. " key count is invalid")
    return value
end

function SL.array_length(value, label, minimum, maximum)
    SL.expect(type(value) == "table", label .. " must be an array")
    SL.expect(SL.json_kind[value] == nil or SL.json_kind[value] == "array", label .. " must not be an object")
    local count = 0
    local highest = 0
    for key in pairs(value) do
        SL.expect(type(key) == "number" and key == math.floor(key) and key >= 1, label .. " has a non-array key")
        count = count + 1
        if key > highest then
            highest = key
        end
    end
    SL.expect(highest == count, label .. " must not contain holes")
    SL.expect(count >= (minimum or 0) and count <= (maximum or count), label .. " length is outside bounds")
    return count
end

function SL.sorted_unique_strings(value, label, validator, maximum)
    local count = SL.array_length(value, label, 0, maximum or 64)
    local out = {}
    local seen = {}
    for index = 1, count do
        local item = validator(value[index], label .. "[" .. index .. "]")
        SL.expect(not seen[item], label .. " contains duplicate " .. item)
        seen[item] = true
        out[index] = item
    end
    table.sort(out)
    return out
end

function SL.strict_json_parse(raw, label, maximum)
    SL.expect(type(raw) == "string", label .. " must be bytes")
    SL.expect(#raw >= 2 and #raw <= (maximum or SL.limits.metadata_bytes), label .. " byte length is outside bounds")
    for index = 1, #raw do
        local byte = raw:byte(index)
        SL.expect(byte == 0x09 or byte == 0x0a or byte == 0x0d or (byte >= 0x20 and byte <= 0x7e),
            label .. " must contain ASCII JSON bytes only")
    end

    local offset = 1
    local function fail_here(message)
        SL.raise(label .. " " .. message .. " at byte " .. (offset - 1))
    end
    local function whitespace()
        while offset <= #raw do
            local byte = raw:byte(offset)
            if byte ~= 0x09 and byte ~= 0x0a and byte ~= 0x0d and byte ~= 0x20 then
                break
            end
            offset = offset + 1
        end
    end
    local function parse_string()
        if raw:sub(offset, offset) ~= '"' then
            fail_here("expected a string")
        end
        offset = offset + 1
        local out = {}
        while offset <= #raw do
            local byte = raw:byte(offset)
            if byte == 0x22 then
                offset = offset + 1
                return table.concat(out)
            end
            if byte == 0x5c then
                offset = offset + 1
                local escaped = raw:sub(offset, offset)
                local simple = { ['"'] = '"', ["\\"] = "\\", ["/"] = "/" }
                if simple[escaped] then
                    out[#out + 1] = simple[escaped]
                    offset = offset + 1
                elseif escaped == "u" then
                    local hex = raw:sub(offset + 1, offset + 4)
                    if #hex ~= 4 or hex:match("^[0-9a-fA-F]+$") == nil then
                        fail_here("has an invalid unicode escape")
                    end
                    local decoded = tonumber(hex, 16)
                    if decoded < 0x20 or decoded > 0x7e then
                        fail_here("string decodes outside printable ASCII")
                    end
                    out[#out + 1] = string.char(decoded)
                    offset = offset + 5
                else
                    fail_here("string escape is not printable ASCII")
                end
            else
                if byte < 0x20 or byte > 0x7e then
                    fail_here("string contains a non-printable byte")
                end
                out[#out + 1] = string.char(byte)
                offset = offset + 1
            end
        end
        fail_here("has an unterminated string")
    end
    local function parse_number()
        local start = offset
        if raw:sub(offset, offset) == "-" then
            offset = offset + 1
        end
        local first = raw:sub(offset, offset)
        if first == "0" then
            offset = offset + 1
            if raw:sub(offset, offset):match("%d") then
                fail_here("has a leading-zero number")
            end
        elseif first:match("[1-9]") then
            repeat
                offset = offset + 1
            until raw:sub(offset, offset):match("%d") == nil
        else
            fail_here("has an invalid number")
        end
        local suffix = raw:sub(offset, offset)
        if suffix == "." or suffix == "e" or suffix == "E" then
            fail_here("uses a non-integer number")
        end
        local token = raw:sub(start, offset - 1)
        if token == "-0" then
            fail_here("uses negative zero")
        end
        local number = tonumber(token)
        if not number or math.abs(number) > 9007199254740991 then
            fail_here("integer is outside the safe range")
        end
        return number
    end

    local parse_value
    parse_value = function(depth)
        if depth > SL.limits.json_depth then
            fail_here("exceeds JSON depth " .. SL.limits.json_depth)
        end
        whitespace()
        local first = raw:sub(offset, offset)
        if first == "{" then
            offset = offset + 1
            whitespace()
            local object = {}
            SL.json_kind[object] = "object"
            if raw:sub(offset, offset) == "}" then
                offset = offset + 1
                return object
            end
            while true do
                local key = parse_string()
                if object[key] ~= nil then
                    fail_here("has duplicate object key " .. key)
                end
                whitespace()
                if raw:sub(offset, offset) ~= ":" then
                    fail_here("expected ':'")
                end
                offset = offset + 1
                object[key] = parse_value(depth + 1)
                whitespace()
                local delimiter = raw:sub(offset, offset)
                if delimiter == "}" then
                    offset = offset + 1
                    return object
                end
                if delimiter ~= "," then
                    fail_here("expected ',' or '}'")
                end
                offset = offset + 1
                whitespace()
            end
        end
        if first == "[" then
            offset = offset + 1
            whitespace()
            local array = {}
            SL.json_kind[array] = "array"
            if raw:sub(offset, offset) == "]" then
                offset = offset + 1
                return array
            end
            while true do
                array[#array + 1] = parse_value(depth + 1)
                whitespace()
                local delimiter = raw:sub(offset, offset)
                if delimiter == "]" then
                    offset = offset + 1
                    return array
                end
                if delimiter ~= "," then
                    fail_here("expected ',' or ']'")
                end
                offset = offset + 1
                whitespace()
            end
        end
        if first == '"' then
            return parse_string()
        end
        if first == "t" and raw:sub(offset, offset + 3) == "true" then
            offset = offset + 4
            return true
        end
        if first == "f" and raw:sub(offset, offset + 4) == "false" then
            offset = offset + 5
            return false
        end
        if first == "n" and raw:sub(offset, offset + 3) == "null" then
            fail_here("uses unsupported null")
        end
        return parse_number()
    end

    whitespace()
    local value = parse_value(1)
    whitespace()
    if offset <= #raw then
        fail_here("has trailing data")
    end
    return value
end

function SL.validate_metadata_base_url(value)
    SL.assert_ascii(value, "metadata_base_url", 1, 400)
    SL.expect(value:sub(-1) ~= "/" and not value:find("%%") and not value:find("\\", 1, true)
        and not value:find("?", 1, true) and not value:find("#", 1, true),
        "metadata_base_url is not normalized")
    local path = value:match("^https://raw%.githubusercontent%.com/(.+)$")
    SL.expect(path ~= nil, "metadata_base_url must use plain HTTPS raw.githubusercontent.com")
    local segments = {}
    for segment in path:gmatch("[^/]+") do
        segments[#segments + 1] = segment
    end
    SL.expect(#segments >= 4 and table.concat(segments, "/") == path,
        "metadata_base_url requires owner/repo/ref/path without empty segments")
    for index = 1, #segments do
        SL.expect(segments[index] ~= "." and segments[index] ~= ".."
            and segments[index]:match("^[A-Za-z0-9_.%-]+$") ~= nil,
            "metadata_base_url has an unsafe path segment")
    end
    return value
end

function SL.validate_module_path(value, label, prefix)
    SL.assert_ascii(value, label, 1, prefix and 200 or 240)
    SL.expect(value:sub(1, 1) ~= "/" and not value:find("//", 1, true)
        and not value:find("\\", 1, true) and not value:find("%%")
        and not value:find("?", 1, true) and not value:find("#", 1, true),
        label .. " has a forbidden path character")
    if prefix then
        SL.expect(value:sub(-1) == "/", label .. " must end with '/'")
        value = value:sub(1, -2)
    else
        SL.expect(value:sub(-4) == ".lua" and value:sub(-1) ~= "/", label .. " must name a .lua file")
    end
    SL.expect(#value > 0, label .. " must not be empty")
    for segment in value:gmatch("[^/]+") do
        SL.expect(segment ~= "." and segment ~= ".." and segment:match("^[A-Za-z0-9_.%-]+$") ~= nil,
            label .. " has an unsafe segment")
    end
    return prefix and (value .. "/") or value
end

function SL.validate_allowed_targets(value)
    local count = SL.array_length(value, "allowed_targets", 1, 16)
    local result = {}
    local seen = {}
    for index = 1, count do
        local rule = SL.exact_keys(value[index], { "owner", "path_prefix", "repo" }, "allowed_targets[" .. index .. "]")
        local owner = SL.valid_owner_repo(rule.owner, "allowed target owner")
        local repo = SL.valid_owner_repo(rule.repo, "allowed target repo")
        local path_prefix = SL.validate_module_path(rule.path_prefix, "allowed target path_prefix", true)
        local identity = owner .. "/" .. repo .. "/" .. path_prefix
        SL.expect(not seen[identity], "duplicate allowed target " .. identity)
        seen[identity] = true
        result[index] = { owner = owner, repo = repo, path_prefix = path_prefix }
    end
    return result
end

function SL.validate_meta_ref(value, label)
    SL.exact_keys(value, { "length", "sha256", "version" }, label)
    SL.assert_integer(value.version, label .. ".version", 1)
    SL.assert_integer(value.length, label .. ".length", 1, 1024 * 1024)
    SL.valid_digest(value.sha256, label .. ".sha256")
    return value
end

function SL.validate_common(signed, role)
    SL.assert_integer(signed.schema, role .. ".schema", 1)
    SL.expect(signed.schema == 1, role .. ".schema must be 1")
    SL.expect(signed.role == role, role .. ".role mismatch")
    SL.valid_id(signed.bundle_id, role .. ".bundle_id")
    SL.valid_id(signed.channel, role .. ".channel")
    SL.assert_integer(signed.version, role .. ".version", 0)
    SL.assert_integer(signed.security_epoch, role .. ".security_epoch", 0)
    SL.assert_integer(signed.issued_at, role .. ".issued_at", 0)
    SL.assert_integer(signed.expires_at, role .. ".expires_at", 0)
    SL.assert_integer(signed.min_loader_version, role .. ".min_loader_version", 0)
    SL.expect(signed.expires_at > signed.issued_at, role .. " expiry must follow issue time")
    SL.expect(signed.expires_at - signed.issued_at <= SL.limits.role_lifetime[role], role .. " lifetime is too long")
end

function SL.validate_targets(signed, allowed_targets)
    SL.exact_keys(signed, {
        "bundle_id", "channel", "entrypoints", "expires_at", "issued_at", "min_loader_version",
        "modules", "role", "rollback_floor", "schema", "security_epoch", "version",
    }, "targets.signed")
    SL.validate_common(signed, "targets")
    SL.assert_integer(signed.rollback_floor, "targets.rollback_floor", 0)
    SL.expect(signed.version >= signed.rollback_floor, "targets.version is below rollback_floor")
    local entrypoints = SL.sorted_unique_strings(signed.entrypoints, "targets.entrypoints", SL.valid_id, 32)
    local module_count = SL.array_length(signed.modules, "targets.modules", 1, SL.limits.module_count)
    local modules = {}
    local module_ids = {}
    local capability_allow = {
        client = true, cvar = true, database = true, entity = true, globals = true,
        json = true, plist = true, renderer = true, ui = true, full_env = true,
    }
    for index = 1, module_count do
        local source = SL.exact_keys(signed.modules[index], {
            "capabilities", "commit", "dependencies", "id", "length", "owner", "path",
            "repo", "sha256", "version",
        }, "targets.modules[" .. index .. "]")
        local module_id = SL.valid_id(source.id, "module id")
        SL.expect(modules[module_id] == nil, "duplicate module id " .. module_id)
        SL.assert_ascii(source.version, module_id .. ".version", 1, 64)
        SL.valid_owner_repo(source.owner, module_id .. ".owner")
        SL.valid_owner_repo(source.repo, module_id .. ".repo")
        SL.expect(type(source.commit) == "string" and #source.commit == 40
            and source.commit:match("^[0-9a-f]+$") ~= nil, module_id .. ".commit must be 40 lowercase hex")
        SL.validate_module_path(source.path, module_id .. ".path", false)
        SL.assert_integer(source.length, module_id .. ".length", 1, SL.limits.module_bytes)
        SL.valid_digest(source.sha256, module_id .. ".sha256")
        local dependencies = SL.sorted_unique_strings(source.dependencies, module_id .. ".dependencies", SL.valid_id, 32)
        local capabilities = SL.sorted_unique_strings(source.capabilities, module_id .. ".capabilities", function(value, label)
            SL.valid_id(value, label)
            SL.expect(capability_allow[value], label .. " is not an allowed capability")
            return value
        end, 10)
        for dependency_index = 1, #dependencies do
            SL.expect(dependencies[dependency_index] ~= module_id, module_id .. " depends on itself")
        end
        local allowed = false
        for rule_index = 1, #allowed_targets do
            local rule = allowed_targets[rule_index]
            if source.owner == rule.owner and source.repo == rule.repo
                and source.path:sub(1, #rule.path_prefix) == rule.path_prefix then
                allowed = true
                break
            end
        end
        SL.expect(allowed, module_id .. " is outside the configured target policy")
        modules[module_id] = {
            id = module_id, version = source.version, owner = source.owner, repo = source.repo,
            commit = source.commit, path = source.path, length = source.length, sha256 = source.sha256,
            dependencies = dependencies, capabilities = capabilities,
        }
        module_ids[#module_ids + 1] = module_id
    end
    table.sort(module_ids)
    for index = 1, #entrypoints do
        SL.expect(modules[entrypoints[index]] ~= nil, "entrypoint " .. entrypoints[index] .. " is missing")
    end
    for index = 1, #module_ids do
        local module = modules[module_ids[index]]
        for dependency_index = 1, #module.dependencies do
            SL.expect(modules[module.dependencies[dependency_index]] ~= nil,
                module.id .. " has missing dependency " .. module.dependencies[dependency_index])
        end
    end
    local visit_state = {}
    local order = {}
    local function visit(module_id, depth)
        SL.expect(depth <= SL.limits.dependency_depth, "dependency graph exceeds depth " .. SL.limits.dependency_depth)
        if visit_state[module_id] == 1 then
            SL.raise("dependency cycle includes " .. module_id)
        end
        if visit_state[module_id] == 2 then
            return
        end
        visit_state[module_id] = 1
        local module = modules[module_id]
        for dependency_index = 1, #module.dependencies do
            visit(module.dependencies[dependency_index], depth + 1)
        end
        visit_state[module_id] = 2
        order[#order + 1] = module_id
    end
    for index = 1, #module_ids do
        visit(module_ids[index], 1)
    end
    return { entrypoints = entrypoints, modules = modules, module_ids = module_ids, order = order }
end

function SL.validate_signed(signed, role, allowed_targets)
    SL.expect(type(signed) == "table", role .. ".signed must be an object")
    if role == "timestamp" then
        SL.exact_keys(signed, {
            "bundle_id", "channel", "expires_at", "issued_at", "min_loader_version", "role",
            "schema", "security_epoch", "snapshot", "version",
        }, "timestamp.signed")
        SL.validate_common(signed, role)
        SL.validate_meta_ref(signed.snapshot, "timestamp.snapshot")
        return nil
    end
    if role == "snapshot" then
        SL.exact_keys(signed, {
            "bundle_id", "channel", "expires_at", "issued_at", "min_loader_version", "role",
            "schema", "security_epoch", "targets", "version",
        }, "snapshot.signed")
        SL.validate_common(signed, role)
        SL.validate_meta_ref(signed.targets, "snapshot.targets")
        return nil
    end
    SL.expect(role == "targets", "unknown metadata role")
    return SL.validate_targets(signed, allowed_targets)
end

function SL.frame(name, value)
    SL.assert_ascii(name, "canonical field name", 1, 64)
    local text = type(value) == "number" and SL.integer_text(value) or value
    SL.assert_ascii(text, "canonical " .. name, 0, 1024)
    return #name .. ":" .. name .. #text .. ":" .. text
end

function SL.canonical_signed(signed, graph)
    local role = signed.role
    local parts = {
        "GSLOADER:" .. role .. ":v1\0",
        SL.frame("schema", signed.schema), SL.frame("role", role),
        SL.frame("bundle_id", signed.bundle_id), SL.frame("channel", signed.channel),
        SL.frame("version", signed.version), SL.frame("security_epoch", signed.security_epoch),
        SL.frame("issued_at", signed.issued_at), SL.frame("expires_at", signed.expires_at),
        SL.frame("min_loader_version", signed.min_loader_version),
    }
    if role == "timestamp" then
        parts[#parts + 1] = SL.frame("snapshot.version", signed.snapshot.version)
        parts[#parts + 1] = SL.frame("snapshot.length", signed.snapshot.length)
        parts[#parts + 1] = SL.frame("snapshot.sha256", signed.snapshot.sha256)
    elseif role == "snapshot" then
        parts[#parts + 1] = SL.frame("targets.version", signed.targets.version)
        parts[#parts + 1] = SL.frame("targets.length", signed.targets.length)
        parts[#parts + 1] = SL.frame("targets.sha256", signed.targets.sha256)
    else
        parts[#parts + 1] = SL.frame("rollback_floor", signed.rollback_floor)
        parts[#parts + 1] = SL.frame("entrypoint_count", #graph.entrypoints)
        for index = 1, #graph.entrypoints do
            parts[#parts + 1] = SL.frame("entrypoint", graph.entrypoints[index])
        end
        parts[#parts + 1] = SL.frame("module_count", #graph.module_ids)
        for index = 1, #graph.module_ids do
            local module = graph.modules[graph.module_ids[index]]
            for _, field in ipairs({ "id", "version", "owner", "repo", "commit", "path", "length", "sha256" }) do
                parts[#parts + 1] = SL.frame("module." .. field, module[field])
            end
            parts[#parts + 1] = SL.frame("module.dependency_count", #module.dependencies)
            for dependency_index = 1, #module.dependencies do
                parts[#parts + 1] = SL.frame("module.dependency", module.dependencies[dependency_index])
            end
            parts[#parts + 1] = SL.frame("module.capability_count", #module.capabilities)
            for capability_index = 1, #module.capabilities do
                parts[#parts + 1] = SL.frame("module.capability", module.capabilities[capability_index])
            end
        end
    end
    return table.concat(parts)
end

function SL.parse_envelope(raw, role)
    local envelope = SL.strict_json_parse(raw, role .. " envelope", SL.limits.metadata_bytes)
    SL.exact_keys(envelope, { "signatures", "signed" }, role .. " envelope")
    local graph = SL.validate_signed(envelope.signed, role, SL.config.allowed_targets)
    local signature_count = SL.array_length(envelope.signatures, role .. ".signatures", 1, 16)
    local signatures = {}
    local seen = {}
    for index = 1, signature_count do
        local signature = SL.exact_keys(envelope.signatures[index], { "key_id", "sig" }, role .. ".signature")
        local key_id = SL.valid_id(signature.key_id, role .. ".signature.key_id")
        SL.expect(not seen[key_id], role .. " has duplicate signature " .. key_id)
        seen[key_id] = true
        local decoded, decode_error = SL.base64_decode(signature.sig, 64)
        SL.expect(decoded ~= nil, role .. " signature encoding failed: " .. tostring(decode_error))
        signatures[index] = { key_id = key_id, sig = signature.sig }
    end
    return { signed = envelope.signed, signatures = signatures, graph = graph }
end

function SL.verify_envelope(raw, role)
    local envelope = SL.parse_envelope(raw, role)
    local policy = SL.config.roles[role]
    local permitted = {}
    for index = 1, #policy.key_ids do
        permitted[policy.key_ids[index]] = true
    end
    local canonical = SL.canonical_signed(envelope.signed, envelope.graph)
    local valid_signers = {}
    for index = 1, #envelope.signatures do
        local signature = envelope.signatures[index]
        SL.expect(permitted[signature.key_id], role .. " has unauthorized signer " .. signature.key_id)
        local key = SL.config.trusted_keys[signature.key_id]
        local verified, verify_error = SL.verify_p256(canonical, signature.sig, key.x, key.y)
        if verified == nil then
            SL.raise(role .. " verifier failure: " .. tostring(verify_error))
        end
        if verified then
            valid_signers[#valid_signers + 1] = signature.key_id
        end
    end
    SL.expect(#valid_signers >= policy.threshold,
        role .. " signature threshold not met (" .. #valid_signers .. "/" .. policy.threshold .. ")")
    table.sort(valid_signers)
    local digest, digest_error = SL.sha256_hex(raw)
    SL.expect(digest ~= nil, digest_error)
    return {
        raw = raw, signed = envelope.signed, graph = envelope.graph,
        valid_signers = valid_signers, digest = digest,
    }
end

function SL.config_foundation_valid()
    local ok, result = pcall(function()
        SL.exact_keys(CONFIG, {
            "allowed_targets", "bundle_id", "channel", "metadata_base_url", "roles", "trusted_keys",
        }, "public trust configuration")
        if CONFIG.metadata_base_url:find("OWNER", 1, true) or CONFIG.metadata_base_url:find("REPOSITORY", 1, true) then
            SL.raise("run publish.mjs configure-loader with production public trust")
        end
        SL.validate_metadata_base_url(CONFIG.metadata_base_url)
        SL.valid_id(CONFIG.bundle_id, "configuration bundle_id")
        SL.valid_id(CONFIG.channel, "configuration channel")
        local allowed_targets = SL.validate_allowed_targets(CONFIG.allowed_targets)
        SL.expect(type(CONFIG.trusted_keys) == "table", "trusted_keys must be an object")
        local trusted_keys = {}
        local key_count = 0
        for key_id, key in pairs(CONFIG.trusted_keys) do
            key_count = key_count + 1
            SL.valid_id(key_id, "trusted key id")
            SL.exact_keys(key, { "x", "y" }, "trusted key " .. key_id)
            local x, x_error = SL.hex_decode(key.x, 32)
            local y, y_error = SL.hex_decode(key.y, 32)
            SL.expect(x ~= nil and y ~= nil, "trusted key " .. key_id .. " has malformed coordinates: "
                .. tostring(x_error or y_error))
            SL.expect(key.x ~= string.rep("0", 64) and key.y ~= string.rep("0", 64),
                "trusted key " .. key_id .. " is still a placeholder")
            trusted_keys[key_id] = { x = key.x, y = key.y }
        end
        SL.expect(key_count >= 1 and key_count <= 16, "trusted key count is outside 1-16")
        SL.exact_keys(CONFIG.roles, { "snapshot", "targets", "timestamp" }, "roles")
        local roles = {}
        for _, role in ipairs({ "timestamp", "snapshot", "targets" }) do
            local policy = SL.exact_keys(CONFIG.roles[role], { "key_ids", "threshold" }, role .. " role policy")
            local key_ids = SL.sorted_unique_strings(policy.key_ids, role .. ".key_ids", SL.valid_id, 16)
            SL.expect(#key_ids >= 1, role .. " role must contain a key")
            SL.assert_integer(policy.threshold, role .. ".threshold", 1, #key_ids)
            for index = 1, #key_ids do
                SL.expect(trusted_keys[key_ids[index]] ~= nil, role .. " references unknown key " .. key_ids[index])
            end
            roles[role] = { threshold = policy.threshold, key_ids = key_ids }
        end
        SL.config = {
            metadata_base_url = CONFIG.metadata_base_url,
            bundle_id = CONFIG.bundle_id,
            channel = CONFIG.channel,
            allowed_targets = allowed_targets,
            trusted_keys = trusted_keys,
            roles = roles,
        }
        return true
    end)
    if not ok then
        return nil, result
    end
    return result
end

function SL.canonical_self_test()
    local signed = {
        schema = 1,
        role = "timestamp",
        bundle_id = "bundle",
        channel = "stable",
        version = 1,
        security_epoch = 2,
        issued_at = 100,
        expires_at = 200,
        min_loader_version = 1,
        snapshot = { version = 3, length = 4, sha256 = string.rep("a", 64) },
    }
    local ok, result = pcall(function()
        SL.validate_signed(signed, "timestamp")
        local payload = SL.canonical_signed(signed)
        local digest, digest_error = SL.sha256_hex(payload)
        SL.expect(digest ~= nil, digest_error)
        SL.expect(digest == "e4131cd0fccb45e7a3ca38f982a987e14c0c84da418f8cf00a2e57b501555a91",
            "metadata canonicalization known-answer mismatch")
        return true
    end)
    if not ok then
        return nil, result
    end
    return result
end

function SL.now()
    SL.expect(type(client) == "table" and type(client.unix_time) == "function", "client.unix_time is unavailable")
    local ok, value = pcall(client.unix_time)
    SL.expect(ok, "client.unix_time failed")
    return SL.assert_integer(value, "current unix time", 0)
end

function SL.check_expected_common(item, now)
    local signed = item.signed
    SL.expect(signed.bundle_id == SL.config.bundle_id, signed.role .. " bundle_id mismatch")
    SL.expect(signed.channel == SL.config.channel, signed.role .. " channel mismatch")
    SL.expect(signed.min_loader_version <= SL.version, signed.role .. " requires a newer loader")
    SL.expect(signed.issued_at <= now + SL.limits.future_skew, signed.role .. " is issued too far in the future")
    SL.expect(signed.expires_at > now, signed.role .. " is expired")
end

function SL.check_high_water(role, item)
    local high_water = SL.state.high_water
    if type(high_water) ~= "table" or type(high_water.roles) ~= "table" then
        return
    end
    local previous = high_water.roles[role]
    if previous == nil then
        return
    end
    SL.exact_keys(previous, { "sha256", "version" }, "high_water." .. role)
    SL.assert_integer(previous.version, "high_water." .. role .. ".version", 1)
    SL.valid_digest(previous.sha256, "high_water." .. role .. ".sha256")
    SL.expect(item.signed.version >= previous.version, role .. " rollback below promoted version")
    SL.expect(item.signed.version ~= previous.version or item.digest == previous.sha256,
        role .. " equivocation: same version has a different digest")
end

function SL.verify_current_role(raw, role, now)
    local item = SL.verify_envelope(raw, role)
    SL.check_expected_common(item, now)
    SL.check_high_water(role, item)
    return item
end

function SL.assert_raw_reference(raw, reference, label)
    SL.expect(type(raw) == "string" and #raw == reference.length, label .. " raw length mismatch")
    local digest, digest_error = SL.sha256_hex(raw)
    SL.expect(digest ~= nil, digest_error)
    SL.expect(digest == reference.sha256, label .. " raw SHA-256 mismatch")
end

function SL.make_candidate_high_water(candidate)
    return {
        security_epoch = candidate.targets.signed.security_epoch,
        rollback_floor = candidate.targets.signed.rollback_floor,
        roles = {
            timestamp = { version = candidate.timestamp.signed.version, sha256 = candidate.timestamp.digest },
            snapshot = { version = candidate.snapshot.signed.version, sha256 = candidate.snapshot.digest },
            targets = { version = candidate.targets.signed.version, sha256 = candidate.targets.digest },
        },
    }
end

function SL.check_chain_epochs_and_floor(candidate)
    local epoch = candidate.timestamp.signed.security_epoch
    SL.expect(candidate.snapshot.signed.security_epoch == epoch and candidate.targets.signed.security_epoch == epoch,
        "metadata security_epoch mismatch")
    local high_water = SL.state.high_water
    if type(high_water) ~= "table" then
        return
    end
    local previous_epoch = SL.assert_integer(high_water.security_epoch or 0, "high_water.security_epoch", 0)
    local previous_floor = SL.assert_integer(high_water.rollback_floor or 0, "high_water.rollback_floor", 0)
    SL.expect(epoch >= previous_epoch, "security_epoch rollback")
    SL.expect(candidate.targets.signed.rollback_floor >= previous_floor, "rollback_floor rollback")
    SL.expect(candidate.targets.signed.version >= previous_floor, "targets below promoted rollback floor")
end

function SL.database_available()
    return type(database) == "table" and type(database.read) == "function"
        and type(database.write) == "function"
end

function SL.db_key(suffix)
    return "shinymoon_loader/" .. SL.config.bundle_id .. "/" .. SL.config.channel .. "/" .. suffix
end

function SL.load_persisted_high_water()
    if not SL.database_available() then
        return
    end
    local ok, row = pcall(database.read, SL.db_key("state"))
    if not ok or type(row) ~= "table" or type(row.high_water) ~= "table" then
        return
    end
    local valid = pcall(function()
        local high_water = row.high_water
        SL.assert_integer(high_water.security_epoch or 0, "high_water.security_epoch", 0)
        SL.assert_integer(high_water.rollback_floor or 0, "high_water.rollback_floor", 0)
        SL.expect(type(high_water.roles) == "table", "high_water.roles must be a table")
        for _, role in ipairs({ "timestamp", "snapshot", "targets" }) do
            local entry = high_water.roles[role]
            if entry ~= nil then
                SL.exact_keys(entry, { "sha256", "version" }, "high_water." .. role)
                SL.assert_integer(entry.version, "high_water." .. role .. ".version", 1)
                SL.valid_digest(entry.sha256, "high_water." .. role .. ".sha256")
            end
        end
    end)
    if valid then
        SL.state.high_water = row.high_water
    else
        SL.log("error", "stored high-water state is malformed and was ignored")
    end
end

function SL.verify_offline_bundle(slot, now)
    SL.expect(type(slot) == "table", "cache slot must be a table")
    local timestamp = SL.verify_current_role(slot.timestamp_raw, "timestamp", now)
    SL.assert_raw_reference(slot.snapshot_raw, timestamp.signed.snapshot, "snapshot")
    local snapshot = SL.verify_current_role(slot.snapshot_raw, "snapshot", now)
    SL.expect(snapshot.signed.version == timestamp.signed.snapshot.version, "timestamp snapshot version mismatch")
    SL.assert_raw_reference(slot.targets_raw, snapshot.signed.targets, "targets")
    local targets = SL.verify_current_role(slot.targets_raw, "targets", now)
    SL.expect(targets.signed.version == snapshot.signed.targets.version, "snapshot targets version mismatch")
    local candidate = {
        timestamp = timestamp, snapshot = snapshot, targets = targets,
        timestamp_raw = slot.timestamp_raw, snapshot_raw = slot.snapshot_raw, targets_raw = slot.targets_raw,
        graph = targets.graph, module_bytes = {}, source = "cache",
    }
    SL.check_chain_epochs_and_floor(candidate)
    SL.expect(type(slot.modules) == "table", "cached modules must be a table")
    local total = 0
    for index = 1, #candidate.graph.module_ids do
        local module = candidate.graph.modules[candidate.graph.module_ids[index]]
        local raw = slot.modules[module.id]
        SL.expect(type(raw) == "string" and #raw == module.length, module.id .. " cached byte length mismatch")
        local digest, digest_error = SL.sha256_hex(raw)
        SL.expect(digest ~= nil, digest_error)
        SL.expect(digest == module.sha256, module.id .. " cached SHA-256 mismatch")
        total = total + module.length
        candidate.module_bytes[module.id] = raw
    end
    SL.expect(total <= SL.limits.bundle_bytes, "cached bundle size exceeds the limit")
    candidate.total_bytes = total
    candidate.high_water = SL.make_candidate_high_water(candidate)
    return candidate
end

function SL.promote_candidate(candidate)
    if not SL.database_available() then
        return nil, "database is unavailable; skipping cache promotion"
    end
    local row = nil
    local ok_read, read_row = pcall(database.read, SL.db_key("state"))
    if ok_read and type(read_row) == "table" then
        row = read_row
    end
    local inactive = (row and row.active_slot == "a") and "b" or "a"
    local slot = {
        timestamp_raw = candidate.timestamp_raw,
        snapshot_raw = candidate.snapshot_raw,
        targets_raw = candidate.targets_raw,
        modules = candidate.module_bytes,
    }
    local ok, promote_error = pcall(function()
        database.write(SL.db_key("slot_" .. inactive), slot)
        local reread = database.read(SL.db_key("slot_" .. inactive))
        SL.verify_offline_bundle(reread, SL.now())
        database.write(SL.db_key("state"), { active_slot = inactive, high_water = candidate.high_water })
    end)
    if not ok then
        return nil, "cache promotion failed: " .. SL.safe_text(promote_error)
    end
    SL.state.high_water = candidate.high_water
    return true
end

function SL.copy_table(source)
    local out = {}
    for key, value in pairs(source) do
        out[key] = value
    end
    return out
end

function SL.readonly(target, label)
    return setmetatable({}, {
        __index = target,
        __newindex = function()
            error(label .. " is read-only", 2)
        end,
        __metatable = false,
    })
end

function SL.make_module_env()
    local env = {
        assert = assert, error = error, ipairs = ipairs, next = next, pairs = pairs,
        pcall = pcall, select = select, tonumber = tonumber, tostring = tostring,
        type = type, unpack = unpack, xpcall = xpcall,
        setmetatable = setmetatable, getmetatable = getmetatable,
        rawget = rawget, rawset = rawset, rawequal = rawequal,
        string = SL.copy_table(string), table = SL.copy_table(table), math = SL.copy_table(math),
    }
    env.string.dump = nil
    if type(bit) == "table" then
        env.bit = SL.copy_table(bit)
    end
    return env
end

function SL.make_client_capability(resources)
    local wrapped = SL.copy_table(client)
    wrapped.set_event_callback = function(event_name, callback)
        SL.assert_ascii(event_name, "event name", 1, 64)
        SL.expect(type(callback) == "function", "event callback must be a function")
        local forwarder = function(...)
            if resources.revoked then
                return
            end
            return callback(...)
        end
        local ok, register_error = pcall(client.set_event_callback, event_name, forwarder)
        SL.expect(ok, "set_event_callback failed: " .. SL.safe_text(register_error))
        resources.events[#resources.events + 1] = { event = event_name, callback = callback, forwarder = forwarder }
    end
    wrapped.unset_event_callback = function(event_name, callback)
        for index = #resources.events, 1, -1 do
            local entry = resources.events[index]
            if entry.event == event_name and entry.callback == callback then
                pcall(client.unset_event_callback, event_name, entry.forwarder)
                table.remove(resources.events, index)
                return
            end
        end
    end
    wrapped.delay_call = function(seconds, callback, ...)
        SL.expect(type(callback) == "function", "delay_call callback must be a function")
        local count = select("#", ...)
        local arguments = { ... }
        local ok = pcall(client.delay_call, seconds, function()
            if resources.revoked then
                return
            end
            callback(unpack(arguments, 1, count))
        end)
        SL.expect(ok, "delay_call scheduling failed")
    end
    return SL.readonly(wrapped, "client capability")
end

function SL.make_capability(name, resources)
    if name == "client" then
        return SL.make_client_capability(resources)
    end
    local source = _G[name]
    SL.expect(type(source) == "table", "capability " .. name .. " is unavailable in this API")
    return SL.readonly(SL.copy_table(source), name .. " capability")
end

function SL.has_capability(module, name)
    for index = 1, #module.capabilities do
        if module.capabilities[index] == name then
            return true
        end
    end
    return false
end

function SL.compile_candidate(candidate)
    SL.expect(type(loadstring) == "function" and type(setfenv) == "function",
        "loadstring/setfenv are unavailable")
    local chunks = {}
    for index = 1, #candidate.graph.order do
        local module_id = candidate.graph.order[index]
        local module = candidate.graph.modules[module_id]
        local raw = candidate.module_bytes[module_id]
        SL.expect(type(raw) == "string" and #raw > 0, module_id .. " source is missing")
        SL.expect(not raw:find("\0", 1, true), module_id .. " contains a NUL byte")
        SL.expect(raw:byte(1) ~= 27, module_id .. " is precompiled bytecode")
        local chunk, compile_error = loadstring(raw, "@shinymoon_module_" .. module_id)
        SL.expect(chunk ~= nil, module_id .. " failed to compile: " .. SL.safe_text(compile_error))
        if not SL.has_capability(module, "full_env") then
            setfenv(chunk, SL.make_module_env())
        end
        chunks[module_id] = chunk
    end
    return chunks
end

function SL.cleanup_bundle(active)
    if type(active) ~= "table" then
        return
    end
    for index = #active.inited, 1, -1 do
        local entry = active.inited[index]
        if type(entry.descriptor.shutdown) == "function" then
            pcall(entry.descriptor.shutdown, entry.ctx)
        end
    end
    active.inited = {}
    active.resources.revoked = true
    if type(client) == "table" and type(client.unset_event_callback) == "function" then
        for index = #active.resources.events, 1, -1 do
            local entry = active.resources.events[index]
            pcall(client.unset_event_callback, entry.event, entry.forwarder)
        end
    end
    active.resources.events = {}
end

function SL.initialize_candidate(candidate, chunks)
    local resources = { revoked = false, events = {} }
    local active = { candidate = candidate, resources = resources, inited = {} }
    local exports = {}
    local ok, init_error = pcall(function()
        for index = 1, #candidate.graph.order do
            local module_id = candidate.graph.order[index]
            local module = candidate.graph.modules[module_id]
            local run_ok, descriptor = pcall(chunks[module_id])
            SL.expect(run_ok, module_id .. " chunk failed: " .. SL.safe_text(descriptor))
            if SL.has_capability(module, "full_env") and type(descriptor) ~= "table" then
                -- signed trusted payload: the chunk body is the script itself
                exports[module_id] = {}
                active.inited[#active.inited + 1] = { id = module_id, descriptor = {}, ctx = nil }
            else
            SL.expect(type(descriptor) == "table" and type(descriptor.init) == "function",
                module_id .. " must return a descriptor with an init function")
            local ctx = {
                module_id = module_id,
                module_version = module.version,
                log = function(message)
                    SL.log("info", module_id .. ": " .. SL.safe_text(message, 200))
                end,
                dependencies = {},
            }
            for capability_index = 1, #module.capabilities do
                local name = module.capabilities[capability_index]
                if name ~= "full_env" then
                    ctx[name] = SL.make_capability(name, resources)
                end
            end
            for dependency_index = 1, #module.dependencies do
                local dependency_id = module.dependencies[dependency_index]
                ctx.dependencies[dependency_id] = exports[dependency_id]
            end
            local init_ok, result = pcall(descriptor.init, ctx)
            SL.expect(init_ok, module_id .. " init failed: " .. SL.safe_text(result))
            exports[module_id] = type(result) == "table" and result or {}
            active.inited[#active.inited + 1] = { id = module_id, descriptor = descriptor, ctx = ctx }
            end
        end
    end)
    if not ok then
        SL.cleanup_bundle(active)
        return nil, init_error
    end
    return active
end

function SL.activate_candidate(generation, candidate)
    if generation ~= SL.state.generation or SL.state.shutdown then
        return
    end
    if SL.state.active ~= nil then
        SL.fail_attempt(generation, "a bundle is already active; reload the loader to update", "verification")
        return
    end
    SL.set_phase("compile", "compiling " .. #candidate.graph.order .. " modules from " .. candidate.source)
    local compiled, chunks_or_error = pcall(SL.compile_candidate, candidate)
    if not compiled then
        SL.fail_attempt(generation, chunks_or_error, "verification")
        return
    end
    SL.set_phase("initialize", "initializing modules in dependency order")
    local active, init_error = SL.initialize_candidate(candidate, chunks_or_error)
    if not active then
        SL.fail_attempt(generation, init_error, candidate.source == "network" and "network" or "verification")
        return
    end
    SL.state.active = active
    SL.state.verified_candidate = nil
    SL.state.failure_category = nil
    if candidate.source == "network" then
        local promoted, promote_error = SL.promote_candidate(candidate)
        if promoted ~= true then
            SL.log("error", promote_error)
        end
    end
    SL.set_phase("active", candidate.source .. " bundle: targets v" .. candidate.targets.signed.version
        .. ", epoch " .. candidate.targets.signed.security_epoch
        .. ", signers " .. table.concat(candidate.targets.valid_signers, ",")
        .. ", " .. #candidate.graph.module_ids .. " modules")
end

function SL.try_cache_fallback(generation)
    if not SL.database_available() then
        return false
    end
    local ok_state, row = pcall(database.read, SL.db_key("state"))
    if not ok_state or type(row) ~= "table" then
        return false
    end
    local first = row.active_slot == "b" and "b" or "a"
    local slots = { first, first == "a" and "b" or "a" }
    for index = 1, 2 do
        pcall(function()
            local slot = database.read(SL.db_key("slot_" .. slots[index]))
            local candidate = SL.verify_offline_bundle(slot, SL.now())
            SL.activate_candidate(generation, candidate)
        end)
        if SL.state.active ~= nil then
            return true
        end
    end
    return false
end

function SL.fail_attempt(generation, message, category)
    if generation ~= SL.state.generation or SL.state.shutdown then
        return
    end
    SL.state.request = nil
    SL.state.verified_candidate = nil
    SL.state.failure_category = category or "verification"
    if category == "network" and not SL.state.cache_attempted and SL.state.active == nil then
        SL.state.cache_attempted = true
        SL.log("error", "network attempt failed (" .. SL.safe_text(message, 200) .. "); trying verified cache")
        local ok, used = pcall(SL.try_cache_fallback, generation)
        if ok and used then
            return
        end
    end
    SL.set_phase("failed", SL.safe_text(message, 300), "error")
end

function SL.setup_ui()
    if type(ui) ~= "table" or type(ui.new_button) ~= "function" then
        return
    end
    pcall(ui.new_button, "LUA", "B", "Shinymoon loader: status / retry", function()
        local detail = SL.state.detail ~= "" and (": " .. SL.state.detail) or ""
        SL.log("info", "phase " .. SL.state.phase .. detail)
        local active = SL.state.active
        if active ~= nil then
            local graph = active.candidate.graph
            for index = 1, #graph.module_ids do
                local module = graph.modules[graph.module_ids[index]]
                SL.log("info", "module " .. module.id .. " v" .. module.version
                    .. " " .. module.sha256:sub(1, 12))
            end
            return
        end
        if SL.state.shutdown or SL.state.phase ~= "failed" then
            return
        end
        if SL.state.retries >= SL.limits.max_retries then
            SL.log("error", "retry limit reached; reload the loader")
            return
        end
        SL.state.retries = SL.state.retries + 1
        local started, start_error = SL.start_network_attempt()
        if not started then
            SL.log("error", "retry failed to start: " .. SL.safe_text(start_error))
        end
    end)
end

function SL.load_http()
    if SL.http then
        return true
    end
    if type(client) ~= "table" or type(client.delay_call) ~= "function" then
        return nil, "client.delay_call is unavailable"
    end
    local ok, module_or_error = pcall(require, "gamesense/http")
    if not ok then
        return nil, "gamesense/http unavailable (unsafe scripts and the library are required): "
            .. SL.safe_text(module_or_error)
    end
    if type(module_or_error) ~= "table" or type(module_or_error.get) ~= "function" then
        return nil, "gamesense/http does not expose get(url, callback)"
    end
    SL.http = module_or_error
    return true
end

function SL.fetch_one(generation, url, maximum, label, callback)
    if generation ~= SL.state.generation or SL.state.shutdown then
        return
    end
    SL.expect(SL.state.request == nil, "network pipeline attempted concurrent requests")
    SL.assert_ascii(url, label .. " URL", 1, 600)
    SL.state.request_serial = SL.state.request_serial + 1
    local request = { generation = generation, id = SL.state.request_serial, done = false, label = label }
    SL.state.request = request

    local function current()
        return not request.done and not SL.state.shutdown and generation == SL.state.generation
            and SL.state.request == request
    end
    local function finish()
        if not current() then
            return false
        end
        request.done = true
        SL.state.request = nil
        return true
    end

    local delay_ok, delay_error = pcall(client.delay_call, SL.limits.request_timeout, function()
        if finish() then
            SL.fail_attempt(generation, label .. " request timed out", "network")
        end
    end)
    if not delay_ok then
        request.done = true
        SL.state.request = nil
        SL.fail_attempt(generation, label .. " deadline scheduling failed: " .. tostring(delay_error), "network")
        return
    end

    local get_ok, get_error = pcall(SL.http.get, url, function(success, response)
        if not finish() then
            return
        end
        if success ~= true or type(response) ~= "table" or response.status ~= 200 then
            local status = type(response) == "table" and response.status or "transport"
            SL.fail_attempt(generation, label .. " request failed with status " .. tostring(status), "network")
            return
        end
        if type(response.body) ~= "string" then
            SL.fail_attempt(generation, label .. " response body is not bytes", "verification")
            return
        end
        if #response.body < 1 or #response.body > maximum then
            SL.fail_attempt(generation, label .. " response size is outside bounds", "verification")
            return
        end
        local callback_ok, callback_error = pcall(callback, response.body)
        if not callback_ok then
            SL.fail_attempt(generation, callback_error, "verification")
        end
    end)
    if not get_ok and finish() then
        SL.fail_attempt(generation, label .. " request setup failed: " .. tostring(get_error), "network")
    end
end

function SL.construct_module_url(module)
    SL.valid_owner_repo(module.owner, module.id .. ".owner")
    SL.valid_owner_repo(module.repo, module.id .. ".repo")
    SL.expect(type(module.commit) == "string" and #module.commit == 40
        and module.commit:match("^[0-9a-f]+$") ~= nil, module.id .. " commit pin is invalid")
    SL.validate_module_path(module.path, module.id .. ".path", false)
    return "https://raw.githubusercontent.com/" .. module.owner .. "/" .. module.repo .. "/"
        .. module.commit .. "/" .. module.path
end

function SL.accept_verified_candidate(generation, candidate)
    if generation ~= SL.state.generation or SL.state.shutdown then
        return
    end
    local final_now = SL.now()
    SL.check_expected_common(candidate.timestamp, final_now)
    SL.check_expected_common(candidate.snapshot, final_now)
    SL.check_expected_common(candidate.targets, final_now)
    SL.state.verified_candidate = candidate
    SL.state.failure_category = nil
    local targets = candidate.targets
    SL.set_phase("candidate_verified", "targets v" .. targets.signed.version .. ", epoch "
        .. targets.signed.security_epoch .. ", " .. #candidate.graph.module_ids .. " modules")
    SL.activate_candidate(generation, candidate)
end

function SL.fetch_candidate_modules(generation, candidate, index)
    if generation ~= SL.state.generation or SL.state.shutdown then
        return
    end
    if index > #candidate.graph.module_ids then
        candidate.high_water = SL.make_candidate_high_water(candidate)
        SL.accept_verified_candidate(generation, candidate)
        return
    end
    local module_id = candidate.graph.module_ids[index]
    local module = candidate.graph.modules[module_id]
    local url = SL.construct_module_url(module)
    SL.set_phase("fetch_module", module_id .. " (" .. index .. "/" .. #candidate.graph.module_ids .. ")")
    SL.fetch_one(generation, url, module.length, "module " .. module_id, function(raw)
        SL.expect(#raw == module.length, module_id .. " byte length mismatch")
        local digest, digest_error = SL.sha256_hex(raw)
        SL.expect(digest ~= nil, digest_error)
        SL.expect(digest == module.sha256, module_id .. " SHA-256 mismatch")
        candidate.module_bytes[module_id] = raw
        SL.fetch_candidate_modules(generation, candidate, index + 1)
    end)
end

function SL.fetch_metadata_chain(generation)
    local now = SL.now()
    local base = SL.config.metadata_base_url
    SL.set_phase("fetch_timestamp", "requesting timestamp.json")
    SL.fetch_one(generation, base .. "/timestamp.json", SL.limits.metadata_bytes, "timestamp", function(timestamp_raw)
        local timestamp = SL.verify_current_role(timestamp_raw, "timestamp", now)
        local candidate = { timestamp = timestamp, timestamp_raw = timestamp_raw, module_bytes = {}, source = "network" }
        SL.set_phase("fetch_snapshot", "timestamp verified by " .. table.concat(timestamp.valid_signers, ","))
        SL.fetch_one(generation, base .. "/snapshot.json", SL.limits.metadata_bytes, "snapshot", function(snapshot_raw)
            SL.assert_raw_reference(snapshot_raw, timestamp.signed.snapshot, "snapshot")
            local snapshot = SL.verify_current_role(snapshot_raw, "snapshot", now)
            SL.expect(snapshot.signed.version == timestamp.signed.snapshot.version, "timestamp snapshot version mismatch")
            candidate.snapshot = snapshot
            candidate.snapshot_raw = snapshot_raw
            SL.set_phase("fetch_targets", "snapshot verified by " .. table.concat(snapshot.valid_signers, ","))
            SL.fetch_one(generation, base .. "/targets.json", SL.limits.metadata_bytes, "targets", function(targets_raw)
                SL.assert_raw_reference(targets_raw, snapshot.signed.targets, "targets")
                local targets = SL.verify_current_role(targets_raw, "targets", now)
                SL.expect(targets.signed.version == snapshot.signed.targets.version, "snapshot targets version mismatch")
                candidate.targets = targets
                candidate.targets_raw = targets_raw
                candidate.graph = targets.graph
                SL.check_chain_epochs_and_floor(candidate)
                local total = 0
                for module_index = 1, #candidate.graph.module_ids do
                    total = total + candidate.graph.modules[candidate.graph.module_ids[module_index]].length
                end
                SL.expect(total <= SL.limits.bundle_bytes, "declared bundle size exceeds the limit")
                candidate.total_bytes = total
                SL.fetch_candidate_modules(generation, candidate, 1)
            end)
        end)
    end)
end

function SL.start_network_attempt()
    if SL.state.shutdown then
        return nil, "loader is shut down"
    end
    if SL.state.active ~= nil then
        return nil, "a bundle is already active; reload the loader to update"
    end
    if SL.state.request ~= nil then
        return nil, "a load attempt is already in flight"
    end
    SL.state.generation = SL.state.generation + 1
    local generation = SL.state.generation
    SL.state.failure_category = nil
    SL.state.verified_candidate = nil
    SL.state.cache_attempted = false
    local loaded, load_error = SL.load_http()
    if not loaded then
        SL.fail_attempt(generation, load_error, "network")
        return nil, load_error
    end
    local ok, start_error = pcall(SL.fetch_metadata_chain, generation)
    if not ok then
        SL.fail_attempt(generation, start_error, "verification")
        return nil, start_error
    end
    return true
end

function SL.shutdown()
    if SL.state.shutdown then
        return
    end
    SL.state.shutdown = true
    SL.state.generation = SL.state.generation + 1
    SL.state.request = nil
    SL.state.verified_candidate = nil
    local active = SL.state.active
    SL.state.active = nil
    pcall(SL.cleanup_bundle, active)
    SL.http = nil
    SL.crypto_close()
    SL.state.phase = "shutdown"
end

function SL.bootstrap_foundation()
    SL.set_phase("crypto_init", "initializing Windows CNG")
    local opened, open_error = SL.crypto_open()
    if not opened then
        SL.set_phase("failed", open_error, "error")
        return
    end
    local tested, test_error = SL.crypto_self_test()
    if not tested then
        SL.crypto_close()
        SL.set_phase("failed", test_error, "error")
        return
    end
    local canonical, canonical_error = SL.canonical_self_test()
    if not canonical then
        SL.crypto_close()
        SL.set_phase("failed", canonical_error, "error")
        return
    end
    local configured, config_error = SL.config_foundation_valid()
    if not configured then
        SL.crypto_close()
        SL.set_phase("configuration_required", config_error, "error")
        return
    end
    SL.set_phase("foundation_ready", "CNG self-tests and public trust shape passed")
    SL.load_persisted_high_water()
    SL.setup_ui()
    SL.start_network_attempt()
end

if type(client) == "table" and type(client.set_event_callback) == "function" then
    pcall(client.set_event_callback, "shutdown", SL.shutdown)
end

SL.bootstrap_foundation()
